name: CI

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deployAndInvokeSCF:
    runs-on: ubuntu-latest
    env:
      SERVERLESS_PLATFORM_VENDOR: tencent
      TENCENT_SECRET_ID: ${{ secrets.TENCENT_SECRET_ID }}
      TENCENT_SECRET_KEY: ${{ secrets.TENCENT_SECRET_KEY }}
      REGION: ap-shanghai
      REDIS_HOST: ${{ secrets.REDIS_HOST_DEV }}
      REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD_DEV }}
      REDIS_PORT: ${{ secrets.REDIS_PORT_DEV }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Run script
        run: node index.js
